### ISSUE TITLE
Some images never finish loading in full

### ISSUE THREAD

**Issue by arildm** [CDH-DevTeam/arosenius-api#5]
On http://aroseniusarkivet.org/#/image/PRIV-4582 the image remains blurred and the spinner keeps spinning. This is not the only one.

This request to the IMGR part of the api gets a 500 error response:

    http://cdh-vir-1.it.gu.se:8004/images/1600x/gkm_diabilder_odaterade_068.jpg

From the systemd log (I suppose it's relevant):

```
Sep 09 16:49:11 cdh-vir-1.it.gu.se arosenius-api[18399]: Error: Command failed: gm convert: Image sequence is required (unable to coalesce image).
Sep 09 16:49:11 cdh-vir-1.it.gu.se arosenius-api[18399]: at ChildProcess.onExit (/appl/cdh/arosenius-api/node_modules/gm/lib/command.js:301:17)
Sep 09 16:49:11 cdh-vir-1.it.gu.se arosenius-api[18399]: at emitTwo (events.js:125:13)
Sep 09 16:49:11 cdh-vir-1.it.gu.se arosenius-api[18399]: at ChildProcess.emit (events.js:213:7)
Sep 09 16:49:11 cdh-vir-1.it.gu.se arosenius-api[18399]: at maybeClose (internal/child_process.js:897:16)
Sep 09 16:49:11 cdh-vir-1.it.gu.se arosenius-api[18399]: at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

**Comment by arildm** [comment]
The `nginx` user was missing write permissions to `/appl/cdh/arosenius-imagedata` and subfolders. I did:

- set `cdhdev:cdhdev` as owner
- add write permissions to group
- added the `nginx` user to the `cdhdev` group

Now it works. I'm not sure how it was working before...
